kind: Deployment
apiVersion: apps/v1
metadata:
  name: kanban-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: tarushi/kanban-image
        ports:
        - containerPort: 80