apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  labels:
    app: react-docker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    #nodePort: 31003
  selector:
    app: todo